### ISSUE TITLE
.NET Core 2.2 support?

### ISSUE THREAD

**Issue by cheverdyukv** [cloudscribe/cloudscribe#524] opened 2018-12-10 20:45 UTC
I just wondering is there plan to support .NET Core 2.2? I'm really would like to try it specially because it has in-process model and can be served inside IIS and not in separate process. It makes site much faster and also uses less memory. 
As  other benefits now IIS can do static and dynamic compression and also many other problems can be fixed easily like ip address of client etc.

**Comment by joeaudette** [comment] 2018-12-10 20:54
you should be able to change that in your app. In due course we will update our templates and libraries, but if you specify netcoreapp2.2 in your app it should override to newer versions of .net framework packages I think. 

ie if our nuget depends on a 2.1.x version of some aspnetcore package but you make your app use 2.2 then it will use 2.2.

**Comment by cheverdyukv** [comment] 2018-12-10 20:57
So you think it will just works and you don't see any issues here?

**Comment by joeaudette** [comment] 2018-12-10 21:04
netcoreapp2.2 can still use netstandard2.0 libraries.

There may be other changes needed or beneficial in the app, I haven't read up on the upgrade steps but I know it is the app that has to be upgraded.

I haven't installed the 2.2 sdk yet but when I do I will compare how new 2.2 apps look in the latest templates from Microsoft and will update my apps and our template accordingly.
I'm in no rush to update the dependencies since once I do that then everyone must use 2.2 to use the latest cloudscribe nugets, whereas as mentioned, if the app depends on newer versions of aspnetcore then that is what will be used even though the cloudscribe nugets depend on 2.1.x, they really depend on >= 2.1.x so it should work fine if the app uses 2.2.

**Comment by cheverdyukv** [comment] 2018-12-10 21:08
I just thinking that there could be areas where it depends on fact that it is out of process such as getting client IP address or something similar. And they could stop working.
I'm pretty sure all other parts will just work.

**Comment by joeaudette** [comment] 2018-12-10 21:14
I don't expect any troubles but let me know if you run into any. I will try to get to that myself soon as I also would like the perf improvements of in process iis. But as long as you install the new hosting bundle on the server, I think it should just work, I'm not aware of code changes that need to be made other than in the app itself changing to 2.2.

I think the iis integration setup by the new hosting bundle should take care of ipaddress issues.

**Comment by cheverdyukv** [comment] 2018-12-10 21:49
I updated app as stated here: https://docs.microsoft.com/en-us/aspnet/core/migration/21-to-22?view=aspnetcore-2.2&tabs=visual-studio
It is pretty trivial. Only 5 files changed:
`
`Blog.dll
`
`Blog.deps.json
`
`Blog.runtimeconfig.json
`
`Blog.Views.dll
`
`web.config
`
after I redeployed them and app started I can that app lost pretty much all styling. All .css, .png and many other files failed to load. I think something is wrong with themes.

**Comment by joeaudette** [comment] 2018-12-10 21:54
when redeploying with a new framework I would be sure to delete all the existing dlls before deploy so nothing extra is left from the previous framework.

for UI issues check browser dev tools, are there 404s etc, check the server logs for errors and warnings also.

**Comment by cheverdyukv** [comment] 2018-12-10 21:55
I just do build and compare with previous deploy. So all other files was unchanged.

**Comment by cheverdyukv** [comment] 2018-12-10 22:01
I can see this in logs:
warn: cloudscribe.Core.Web.Controllers.Mvc.OopsController[0]
      handled 404 for url: /main/css/style.min.css from ipaddress 70.95.76.33
warn: cloudscribe.Core.Web.Controllers.Mvc.OopsController[0]
      handled 404 for url: /main/js/jquery.min.js from ipaddress 70.95.76.33
warn: cloudscribe.Core.Web.Controllers.Mvc.OopsController[0]
     handled 404 for url: /main/js/bootstrap.bundle.min.js from ipaddress 70.95.76.33

**Comment by joeaudette** [comment] 2018-12-10 22:30
Are those files below the main wwwroot folder or below a theme specific wwwroot?

If in a theme specific folder I would try copying them to the same path below main wwwroot.
Maybe something changed in static files middleware that broke the resolution to find the theme specific static files.

**Comment by cheverdyukv** [comment] 2018-12-10 22:34
It looks like that:
![image](https://user-images.githubusercontent.com/18220536/49765934-b3608880-fc88-11e8-887c-c955501fd4e5.png)

**Comment by cheverdyukv** [comment] 2018-12-10 22:35
And all .dlls are in main directory

**Comment by cheverdyukv** [comment] 2018-12-10 22:36
![image](https://user-images.githubusercontent.com/18220536/49766052-f589ca00-fc88-11e8-93b0-0c2c028ea3b6.png)

**Comment by cheverdyukv** [comment] 2018-12-10 22:39
Looks like it is looking files that are in wwwroot but one level higher.
So when it is looking for 
handled 404 for url: /main/js/jquery.min.js from ipaddress 70.95.76.33
but file located in /main/wwwroot/js/jquery.min.js

**Comment by joeaudette** [comment] 2018-12-10 22:43
I'm talking about the 404s, when I see a 404 for /main/css/style.min.css
I assume main is the name of a theme, otherwise it should not be part of the url unless your site is at somedomain/main rather than somedomain/.

If it is a theme name then my question was does that file and the other 404 files live under /sitefiles/themes/main/wwwroot or under the normal wwwroot folder, and if under site files my suggestion was to try copying them below the normal wwwroot folder.

But if main is not the name of your theme, then I think the files are not in the right place in your hosting.
It seems like the real root of your hosting is one folder up from main in that case.

**Comment by joeaudette** [comment] 2018-12-10 22:47
if main is the actual web root then it should not be in the url for static files, it should map to /

**Comment by joeaudette** [comment] 2018-12-10 22:48
and the static file middleware should resolve wwwroot also as / and the theme specific wwwroot folder also as  /

**Comment by cheverdyukv** [comment] 2018-12-10 22:59
Hmm. It is a bit confusing. Main is also theme name.
As for files:
style.min.css located 
main\SharedThemes\main\wwwroot\css\style.min.css
jquery.min.js located
main\SharedThemes\main\wwwroot\js\jquery.min.js
main\wwwroot\js\jquery.min.js
bootstrap.bundle.min.js located
main\SharedThemes\main\wwwroot\js\bootstrap.bundle.min.js
main\wwwroot\js\bootstrap.bundle.min.js

**Comment by cheverdyukv** [comment] 2018-12-10 23:01
When I tested this:
http://www.mysite.com/robots.txt
it works and returns file from wwwroot

**Comment by joeaudette** [comment] 2018-12-10 23:37
ok, so main is a theme then it makes more sense and again sounds like something changed in static files middleware. 

As a workaround I would copy file from /sharedthemes/main/wwwroot into the normal /wwwroot folder
to solve the 404s. I would say "main" wwwroot but that would be ambiguous :-D

If that fixes it then it is a good clue that something changed and I will need to look into it and solve it for 2.2 

I sort of remember maybe they mentioned some change about static files in the asp.net core community standup videos but I forgot what it was.

**Comment by cheverdyukv** [comment] 2018-12-10 23:43
I copied /SharedThemes/main/wwwroot into /wwwroot/main and it works again. But only for main site.
For sub sites it have urls like this:
http://www.mirabulus.com/site1/main/js/jquery.min.js
and it obviously failed to work

**Comment by cheverdyukv** [comment] 2018-12-10 23:50
I also checked how it works after I reverted back to .Net Core 2.1 and I can see that url still 
http://www.mysite.com/site1/main/css/style.min.css
but it works correctly.

**Comment by joeaudette** [comment] 2018-12-11 13:00
Experimenting here this morning I am able to reproduce the problem locally by updating a newly created cloudscribe app to 2.2. It seems to break all shared and per site themes, only the default theme works because its css and js is in the main wwwroot folder.

Investigating...

**Comment by cheverdyukv** [comment] 2018-12-11 16:19
You can leave bug in ASP.NET Core 2.2 repo

**Comment by joeaudette** [comment] 2018-12-11 16:36
I've just published updated nugets that solve the theme problems under 2.2

Strangely the problem I'm having with routing is only in the source solution for cloudscribe core, I can't reproduce the problem anywhere else so far, I've just tested a project created with our template and upgraded to 2.2 with the latest cloudscribe nugets and it works fine.

**Comment by joeaudette** [comment] 2018-12-11 16:40
for information the theme problems were cause by change in behavior of Directory.GetCurrentDirectory() which is mentioned in the comments on the release announcement here: https://blogs.msdn.microsoft.com/dotnet/2018/12/04/announcing-net-core-2-2/

So for the custom theme wwwroot folders I had to update it to use IHostingEnvironment.ContentRootPath instead and that solved the 404 issues for shared themes and site specific themes.

All the cloudscribe nugets still reference 2.1 but as mentioned the app references take precedence.

Please let me know if you agree this issue can be closed.

**Comment by cheverdyukv** [comment] 2018-12-11 16:50
GetCurrentDirectory is pure evil :) Every time I use it I regret it.
I will try to use it today and let you know result.

**Comment by joeaudette** [comment] 2018-12-11 16:53
AppContext.BaseDirectory also changed behavior. I found it resolved to C:\Program Files\IIS Express which is also what Directory.GetCurrentDirectory() was resolving to. Whereas in 2.1 it resolved to the app folder.
In any case environment.ContentRootPath is a much cleaner and hopefully future proof solution to get the app directory.

**Comment by cheverdyukv** [comment] 2018-12-11 23:20
It works much better but now all images that I uploaded in blog posts returns 404.
Then I realized that I saw setting SiteUploadFilesRootFolderName and it is now siteuploadfiles instead of sitefiles. After renaming that folder it works.

But when I attempt to insert picture list of available images are empty. And if I upload image it will upload into site **s1** but I'm adding post to site **s3**.

And when I try to send comment to post I got "Unable to add comment" and there is nothing in System Log

**Comment by cheverdyukv** [comment] 2018-12-11 23:30
Also looks like site settings are off. For example I selected one site where I set days to comment to 90 and file in projectsettings contains "DaysToComment": 90 but UI shows No Limit. The same happens for Teaser mode. I did set it to:
    "TeaserMode": 3,
    "TeaserTruncationMode": 0,
    "TeaserTruncationLength": 120
but UI shows 
![image](https://user-images.githubusercontent.com/18220536/49836987-95af2400-fd59-11e8-8c98-03934b9e7da4.png)
and I cannot leave comments on posts older than 90 days. There is no even UI for that.

**Comment by joeaudette** [comment] 2018-12-11 23:42
some of these issues sound like file system permissions on the nodb files, if it can't save a comment, can't save settings and maybe can't write errors to the log.

I will look into these issues tomorrow and see if I can produce them.

**Comment by cheverdyukv** [comment] 2018-12-12 00:19
Just to summarize list of issues:
1. I could create post without any problem.
2. I could upload file without problem.
3. I checked permissions at my hosting provider and logs, nodb_storage, siteuploadfiles has R/W permissions.
4. I can see System log entries for other errors.
5. Email works fine.
6. But I cannot post comment due to AJAX request failed with 400 error. AJAX request does not contain site name (ie http://www.mysite.com/blog/ajaxpostcomment). There is nothing in System log. If I try to open invalid Url I can see that error in System log.
7. When I edit post and attempt to insert picture there are no images and if I upload one it will upload to wrong site. But image is inserted correctly and post created and displayed successfully. 
8. After I reverted to .Net 2.1 commenting started to work fine. But AJAX request changed from http://www.mysite.com/blog/ajaxpostcomment to http://www.mysite.com/**site3**/blog/ajaxpostcomment
9. After I reverted to .Net 2.1 and inserting image when I edit post it will upload image to correct site and list of images is not empty.
10. After I reverted to .Net 2.1 post I created when it had .Net 2.2 still displaying correctly even picture is located in site s1. Perhaps there is another bug because I believe it should not load images for post in site s3 from site s1. I could be wrong here. 
11. Site's Content Settings are still wrong even in .Net Core 2.1, so I think there is some unrelated problem.

**Comment by joeaudette** [comment] 2018-12-12 12:16
>Then I realized that I saw setting SiteUploadFilesRootFolderName and it is now siteuploadfiles instead of sitefiles. After renaming that folder it works.

That setting is only populated new projects created with the latest template. For existing projects since it is not set the default value would be "sitefiles" so it would not change where files are uploaded for existing projects unless you add that setting yourself. It was intended for making things more docker friendly but if you change it in an existing project then you also need to move the files as you have done but also need to edit LocalMediaVirtualPath in nodb_storage/....../projectsettings/guid.json to be "/media/images/"

you would have to do that for each tenant


There definitely seems to still be some routing issues.

I'm finding some links are broken in folder sites.

A workaround for all the problems is to turn off the new endpoint routing, I think it has some bugs.

    services.AddMvc(options => {
                options.EnableEndpointRouting = false;
            })
                .AddRazorOptions(options =>
                {
                    options.ViewLocationExpanders.Add(new cloudscribe.Core.Web.Components.SiteViewLocationExpander());
                })
                .SetCompatibilityVersion(CompatibilityVersion.Version_2_2);

after doing that I'm not seeing any problems with blog comments or image uploading

We may have to live with that workaround for now until the bugs can be isolated and reported or worked around somehow. I think this workaround is only needed for cloudscribe installations that use folder tenants.

**Comment by joeaudette** [comment] 2018-12-12 12:33
there are a number of reported issues related to routing that may be relevant to the issues we are seeing
https://github.com/aspnet/AspNetCore/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+routing

in any case the changes to endpoint routing don't provide major benefits in 2.2 but mainly are trying to stabilize it for new features coming in 3.0, so I don't see a major concern about turning it off to solve these problems for now.

**Comment by joeaudette** [comment] 2018-12-12 13:10
I've logged an issue here https://github.com/aspnet/AspNetCore/issues/4591

**Comment by cheverdyukv** [comment] 2018-12-12 18:53
All problems solved. Except #10 but perhaps it is way it is suppose to be.

**Comment by joeaudette** [comment] 2018-12-12 18:56
I'm going to keep this open until I update the project template to use 2.2.
I'm not sure if 2.2 sdk ships in the latest update of VS since I already installed it but want to wait just a little before updating the project template to be sure.

**Comment by joeaudette** [comment] 2018-12-12 18:57
as far as your item 10, there is no protection on static resources, if a file is accessible by url it can be used in content, so that is not a bug.

**Comment by cheverdyukv** [comment] 2018-12-12 19:20
I think we can ignore #10. Due to bugs image inserted as "/img_05122018_085638_0.png" but when I try to edit it after fix it will look like "/site1/img_05122018_085638_0.png" and works correctly.

**Comment by cheverdyukv** [comment] 2018-12-13 18:13
Just as update I did a lot of editing, adding posts and everything works fine so far.

**Comment by joeaudette** [comment] 2018-12-13 18:14
Glad to hear that!

**Comment by ekarlso** [comment] 2019-01-03 09:08
Hi yes everything works fine except that if you try to upgrade IdentityServer4 to 2.3.x then it breaks.

**Comment by joeaudette** [comment] 2019-01-03 12:02
@ekarlso looking at changes in identityserver, it looks like they have made some model changes that will require us to update accordingly and generate new ef migrations in order to use 2.3.x.

I don't think it is related to netcoreapp2.2 though I notice their host sample is still using netcoreapp2.1 and I see where they had updated to 2.2 bu then reverted when I review their commits.

I've created a new issue to track that as I don't see it related to this one.
https://github.com/cloudscribe/cloudscribe/issues/538

**Comment by joeaudette** [comment] 2019-01-04 18:09
@ekarlso fyi, I've updated our idserver integration to the latest idserver version and published updated nugets

**Comment by joeaudette** [comment] 2019-04-13 12:51
Just a note about why the cloudscribe project template so far still creates projects that target netcoreapp2.1

You can see from the chart here: https://github.com/dotnet/announcements/issues/108
That VS 2017 ships with 2.1 sdk and 2.2 must be added manually, so to keep a good out of the box experience for our VS extension we have waited to update the project template.
VS 2019 ships with 2.2 sdk built in so we should be able to update our project templates soon to use 2.2 sdk by default. In the meantime it is very easy to manually change to netcoreapp2.2 as indicated above.

So at the moment we have a good out of the box experience for VS 2017, but could have a not so good experience for someone who does a clean install of VS 2019 on a machine that does not already have the 2.1 sdk.

**Comment by joeaudette** [comment] 2019-04-20 14:03
I've just published v1.75 of our project [template for VS](https://marketplace.visualstudio.com/items?itemName=joeaudette.cloudscribeProjectTemplate) and for [dotnet new](https://www.nuget.org/packages/cloudscribe.templates/1.0.75). The latest project template target netcoreapp2.2 so closing this issue now.

**Closed by joeaudette** 2019-04-20 14:03 UTC
