### ISSUE TITLE
Clear SMTP settings from the UI... "Port" cannot be cleared

### ISSUE THREAD

**Issue by CrispinF** [cloudscribe/cloudscribe#459] opened 2018-08-16 14:45 UTC
Very minor issue, but when following your recommendation to keep SMTP settings for a single-tenant site in appsettings.Production.json we try to clear out the settings from the UI, but find we cannot empty the Port field as it required. Pretty sure earlier I was getting client-side validation, but now when I try again I get a crash and this in the log:
Error 82.69.43.209 Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware /siteadmin/mailsettings 
An unhandled exception has occurred while executing the request

Obviously it doesn't really matter if this is left with some number in it, and all other settings blank, but it's a bit confusing.

**Comment by paulvanbladel** [comment] 2018-08-20 09:54
If it disturbs, delete it from the site table directly in the database.

**Comment by joeaudette** [comment] 2018-08-20 11:33
SMTP port is a non nullable field in the database and therefore is required to have an integer value even if not using smtp, it has a default value of 25 and that should be left alone. 
Really if smtp server is left blank it is sufficient to detect that smtp is not configured.

In my testing client side validation works fine, I cannot reproduce the problem.

**Comment by paulvanbladel** [comment] 2018-08-20 11:58
Ooops, sorry Joe, for giving the wrong advise.

**Comment by joeaudette** [comment] 2018-08-20 12:01
I'm looking into this now, by removing client side validation temporarily I was able to get an error so I will solve that and then put the client side validation back.

**Comment by joeaudette** [comment] 2018-08-20 18:37
This is fixed in the latest nuget packages.

**Closed by joeaudette** 2018-08-20 18:37 UTC
