### ISSUE TITLE
Allow user to change their email address (unless configured not to)

### ISSUE THREAD

**Issue by CrispinF** [cloudscribe/cloudscribe#711] opened 2020-05-04 22:34 UTC
Not possible at present, but definitely required in the real world.
If we can make this simple without any collateral damage, it should be the default that a user can change their email. 
It must also be configurable to prevent this, which would be desirable in an environment where email addresses are assigned rather than under the user's control.
It should not be possible to change email to the same as another existing user for the site/tenant.
If a site has email verification configured this would have to happen again on the change.
Plus - need to review whether any other data relates off email rather than the user's id.

**Comment by CrispinF** [comment] 2020-05-05 16:05
Note that table cs_User already has fields NewEmail and NewEmailApproved so clearly this functionality has been planned at least. Need to check what else already in place.

**Comment by StewartBellamy** [comment] 2020-05-06 07:06
I recently implemented a solution for this elsewhere with a few features:

- When the email change is requested an activation email is sent out
- If the link in the activation email is not clicked within a certain time the activation is invalidated
- Current/new email and password need to be entered on the activation page
- Emails can be sent out to both the new and old addresses
- Generic activation database table with activation guid, activation type etc.  This means you don't have to add lots of columns to exisiting tables, provides more flexibility and opportunity for re-use.

**Comment by SimonAnnetts** [comment] 2020-05-06 13:49
@StewartBellamy did you implement this in Cloudscribe or in another project?

**Comment by StewartBellamy** [comment] 2020-05-06 13:50
@SimonAnnetts  - Another project.

**Comment by JimKerslake** [comment] 2020-12-16 09:16
Duplicate of #738 
Implemented - didn't need to use the Db storage fields 
(used Microsoft base classes for generating a round-trip token which contains encrypted new e-mail and user-id values)

**Closed by JimKerslake** 2020-12-16 09:16 UTC
Labels: enhancement
