### ISSUE TITLE
Pasting into CKEditor has stopped working recently

### ISSUE THREAD

**Issue by CrispinF** [cloudscribe/cloudscribe#884] opened 2023-03-05 18:51 UTC
Using menu button or right-click menu results in a prompt

![image](https://user-images.githubusercontent.com/10574730/222979876-713a66e9-fcc4-423e-8dfd-a70a5a6bccee.png)
 or 
![image](https://user-images.githubusercontent.com/10574730/222979887-e87f8ebe-88f2-482c-b4d3-eedc82f70b5f.png)

but pasting with the keyboard doesn't work either.

Tested in Chrome and Edge.

Might be resolved by the upgrade to CK Editor - #726 - needs testing.

**Comment by JimKerslake** [comment] 2023-03-06 10:56
After a quick test - I think this is probably caused by the upgrade, not resolved by it.
On an existing site  (LHLP) which is still using the older version of CkEditor, then Ctrl-V works fine for me in Chrome and Edge.

More investigation - this seems to be caused by a broken cloudscribe plugin:
cloudscribe-filedrop
which captures the onPaste event and then bombs out when there is no file object n the clipboard.

@SimonAnnetts I will leave a candidate fix in a PR for you to review... there may be more to it than that.

**Comment by SimonAnnetts** [comment] 2023-03-07 14:23
Tested and now working.

**Comment by SimonAnnetts** [comment] 2023-03-08 12:01
cloudscribe.Web.StaticFiles @ 6.0.7. Uploaded to nuget.org.

**Comment by SimonAnnetts** [comment] 2023-03-09 17:01
cloudscribe.Web.StaticFiles @ 6.0.8

**Comment by SimonAnnetts** [comment] 2023-03-09 17:04
pushed to nuget.org

**Comment by SimonAnnetts** [comment] 2023-03-14 14:28
I always do a SHIFT F5 to reload everything after updating js or css files. Not sure there is any other way to force the browser to reload when cloudscribe.Web.StaticFiles has been rebuilt?

**Comment by CrispinF** [comment] 2023-03-14 14:57
@SimonAnnetts can the asp-append-version="true" tag helper be used in reference to the scripts?

**Comment by JimKerslake** [comment] 2023-03-14 15:36
Yes the shift reload was not enough for me - presumably because of the extra ?t=MAUD  
whatever Maud is doing there ;)
Had to go and explicitly visit that URL, with Maud on the end, and then thump the keyboard a bit.
I'm not sure how append-version would interact with this extra bit of Query-string requirement.

I'm also getting the attached a fair bit now, sporadically, when submitting edits that include freshly make hyperlinks
![image](https://user-images.githubusercontent.com/39943820/225053664-3fd74b36-00a2-479f-b927-0ea44c9b8a14.png)

**Comment by SimonAnnetts** [comment] 2023-03-15 09:39
@JimKerslake can you reliably reproduce this issue via the new ckeditor?

**Comment by JimKerslake** [comment] 2023-03-15 09:49
@SimonAnnetts  Sadly no - it happened to me 4 times during an afternoon's editing of existing pages (just adding more hyperlinks) but when I tried to provoke it deliberately, I failed.  I don't think there was anything in the log. Maybe just watch out for it at the moment - again might have been due to a cached old JS file, perhaps.

**Closed** 2023-04-05 14:41 UTC
Labels: bug, completed
