### ISSUE TITLE
InProcess Hosting; Upload issues

### ISSUE THREAD

**Issue by Externaluse** [cloudscribe/cloudscribe#633] opened 2019-05-10 06:55 UTC
Versions: Simple Content 4.0.13; Core.Web 3.1.86, Simple Content.Web 4.0.37; Net.Core 2.2.4

This may be related to changing CS to run as InProcess Hosting aimed at running in IIS - the upload, file manager etc stopped working properly.
My .csproj: 
....
    TargetFramework netcoreapp2.2
    AspNetCoreHostingModel inprocess
...
Create Folder in /filemanager/filedialog does create a folder, but it is not displayed. Type "test" in the folder path, press create folder - apparently nothing happens - but response payload is:
`{"Succeeded":false,"Message":"Folder` already `exists"}`
![image](https://user-images.githubusercontent.com/14993667/57507209-07ce6980-72f6-11e9-8164-ab62553f0b0c.png)

After uploading a file in localhost, getfiletreejson obtains a list, but the display is odd:
`[{"Text":"media","Icon":"far fa-folder","ExpandedIcon":"far fa-folder-open","Image":null,"Selectable":true,"Id":"/media","Class":null,"Tooltip":null,"LazyLoad":true,"Type":"d","MediaType":null,"MimeType":null,"CanPreview":false,"VirtualPath":"/media","Created":"\/Date(1547063365741+0000)\/","Modified":"\/Date(1547063365744+0000)\/","Size":0},{"Text":"test","Icon":"far fa-folder","ExpandedIcon":"far fa-folder-open","Image":null,"Selectable":true,"Id":"/test","Class":null,"Tooltip":null,"LazyLoad":true,"Type":"d","MediaType":null,"MimeType":null,"CanPreview":false,"VirtualPath":"/test","Created":"\/Date(1557469632505+0100)\/","Modified":"\/Date(1557469632505+0100)\/","Size":0},{"Text":"testing","Icon":"far fa-folder","ExpandedIcon":"far fa-folder-open","Image":null,"Selectable":true,"Id":"/testing","Class":null,"Tooltip":null,"LazyLoad":true,"Type":"d","MediaType":null,"MimeType":null,"CanPreview":false,"VirtualPath":"/testing","Created":"\/Date(1557470011153+0100)\/","Modified":"\/Date(1557470011153+0100)\/","Size":0},{"Text":"2015-nsr-tracking-ws.png","Icon":"far fa-file-image","ExpandedIcon":null,"Image":null,"Selectable":true,"Id":"/2015-nsr-tracking-ws.png","Class":null,"Tooltip":null,"LazyLoad":false,"Type":"f","MediaType":"image","MimeType":"image/png","CanPreview":true,"VirtualPath":"/2015-nsr-tracking-ws.png","Created":"\/Date(1557470195622+0100)\/","Modified":"\/Date(1557470195747+0100)\/","Size":353530}]`

![image](https://user-images.githubusercontent.com/14993667/57507444-bd99b800-72f6-11e9-9cad-4345891c0b85.png)

Using the Drag&Drop functionality to upload an image, this happens:
HTTP200 OK on dropfile:
[{"ResizedUrl":"/media/images/s-l1600-ws.jpg","ThumbUrl":"","OriginalUrl":"/media/images/s-l1600.jpg","Name":"s-l1600.jpg","Length":86926,"Type":"image/jpeg","DataId":null,"ErrorMessage":null}]

The file has been written to the server into sitefiles/.../wwwroot/media/images

followed by a 302 GET to /undefined

Due to this, the drag&drop image is inserted as `<img alt=" " src="undefined" />`

I'm not sure about the best way to further investigate this issue.

**Comment by Externaluse** [comment] 2019-05-10 07:12
This may also not be related to InProcess hosting. Disabling the setting on localhost did not change the result, the filedialog appears identically

**Comment by joeaudette** [comment] 2019-05-10 11:55
Sorry but I cannot reproduce the problem. I create a new project with our latest project template. The latest project template does use netcoreapp2.2 and in process hosting.
I update the project to all the latest nugets and test the file manager, it works fine for me creating folders and uploading files.

I would make sure you have disabled endpoint routing as that does have bugs in aspnet core 2.2 that will be fixed in 3. ie in the project generated by our template we have this:

    services.Configure<MvcOptions>(options =>
            {
                //https://github.com/aspnet/AspNetCore/issues/4591
                options.EnableEndpointRouting = false;

                if (sslIsAvailable)
                {
                    options.Filters.Add(new RequireHttpsAttribute());
                }

                options.CacheProfiles.Add("SiteMapCacheProfile",
                     new CacheProfile
                     {
                         Duration = 30
                     });


                options.CacheProfiles.Add("RssCacheProfile",
                     new CacheProfile
                     {
                         Duration = 100
                     });
            });


Note  options.EnableEndpointRouting = false;

If you don't have that it could be a factor.

**Closed** 2019-05-10 18:20 UTC
