### ISSUE TITLE
The link in  confirmation mail does not honour the original redirect url

### ISSUE THREAD

**Issue by paulvanbladel** [cloudscribe/cloudscribe#646] opened 2019-07-04 10:39 UTC
![image](https://user-images.githubusercontent.com/4886272/60659129-ee105500-9e54-11e9-9f17-52d501df6ca0.png)

When both options are selected following flow happens
1. user tries to login from an app (e.g. a spa) managed by Cloudscribe/Ids and want to create a new account
2. user provides username/w
3. user receives email for conforming his email (since the admin still needs to confirm, the email does not forward the user to the app !)
4. admin receives email new registration arrived
5. admin approves the user
6. user receives confirmation mail.
The problem with that mail is the the original redirect url is no longer included.

Note that when the require approval option is deselected in the security settings, the user receives of course the confirm email account email, in that email the redirect URL is just working fine.

I'm testing against the very latest nuget bits of cloudscribe.

**Comment by joeaudette** [comment] 2019-07-04 12:12
There is always a trade off between extra security vs convenience to users.

We've done what we can to make the registration and login convenient to the user, we pass the url of the page the user was on when he clicked register or login as the return url making the assumption that the user wants to return to that page after registration or login. That is an assumption and may not actually be true that the user cares about that. In any case we flow that return url through the user's actions so if confirmed email is required after success registering we can pass it to the link in the email because it is triggered by the same user's action.

When you add the requirement for approval you choose to break the flow of registration in favor of extra security and some convenience is lost in the tradeoff.

The user account may not be approved for some time or not at all, but in any case when it is approved the email is triggered not by the registering user but by the admin user who is doing the approval and at the point we have no idea what page the original user was on so we don't have that information to include in a link and in any case the more time has passed the less the original assumption about where the user wants to land after login is less relevant. Surely the user can find the page if he is still interested at this point.

The only way to solve this would be to capture in the db the return url for the user who is waiting for approval and that seems like a lot of work for an assumption about what the user wants to do after they finally get to login and may in fact be pushing the assumption too far and sending the user to a page that he was on but was only random that he was on that page when decided to register so he may find it unexpected to be redirected there 3 days later when his account is approved. Someone would later report that as a bug.

To avoid breaking the flow and inconveniencing the user consider whether you really need to approve new users or not, if you do then accept the minor inconvenience tradeoff.

I suppose one thing we could do is provide the new user notification even without the approval requirement, ie if the notify email is populated we could notify the admins of the new user account even if they don't need approval. This would allow the scenario to let the user in but wait till admin has time to review before adding a role that might grant the user more access or rejecting/locking the account.

**Comment by paulvanbladel** [comment] 2019-07-04 16:07
Joe
Thanks a lot for the detailed answer. Sure I understand now better how the actual flow is broken and that it is admin driven. Makes perfectly sense.
The additional event you mention would be indeed useful.
Enjoy summer.
Thanks a lot

**Comment by joeaudette** [comment] 2019-07-04 18:57
I've created a new issue #647 and closing this one.

**Closed by joeaudette** 2019-07-04 18:57 UTC
